// <auto-generated />
namespace Schedule_CodeFirstModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class university_teacher_foreign_key : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(university_teacher_foreign_key));
        
        string IMigrationMetadata.Id
        {
            get { return "201805201132007_university_teacher_foreign_key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
